variables:
  DATE_TODAY:
    value: "Saturday"
    description: "my test value"
  DATE_TOMORROW:
    value: ""
    description: "my test value 2"
    
stages:
  - build
  - build2

say_hostname:
  stage: build
  tags: [powershell]    
  when: manual
  script: ./scripts/hostname.ps1

say_date:
  stage: build
  tags: [powershell]  
  when: manual
  script: ./scripts/date.ps1

say_date:
  stage: build2
  tags: [powershell]  
  when: manual
  script: ./scripts/date.ps1