variables:
  PIPELINE_NAME:
    value: ""
    description: "choose from: simple_dependency.yml"
    
include:
  - local: /pipelines/templates/simple_dependency.yml
    rules:
      - if: $PIPELINE_NAME == "simple_dependency"