stages:
  - build
  - build2

say_hostname:
  stage: build
  tags: [powershell]    
  script: ./scripts/hostname.ps1

say_date:
  stage: build
  tags: [powershell]  
  script: ./scripts/date.ps1

say_date:
  stage: build2
  tags: [powershell]  
  script: ./scripts/date.ps1