variables:
  DATE_TODAY:
    value: "Saturday"
    description: "my test value"
  DATE_TOMORROW:
    value: ""
    description: "my test value 2"
    
stages:
  - build
  - summary

say_hostname:
  stage: build
  tags: [powershell]    
  when: manual
  script: ./scripts/hostname.ps1

say_date:
  stage: build
  tags: [powershell]  
  when: manual
  script: ./scripts/date.ps1

say_date:
  stage: build2
  tags: [powershell]  
  when: manual
  script: ./scripts/date.ps1

say_hurray:
  stage: summary
  tags: [powershell]  
  when: on_success
  script: echo "Yes, the pipeline succeeded!"

say_booo:
  stage: summary
  tags: [powershell]  
  when: on_failure
  script: echo "Booo, the pipeline failed :("