variables:
  PIPELINE_NAME:
    value: ""
    description: "choose from: simple_dependency.yml"
    
include:
  - local: /pipelines/simple_dependency.yml
    rules:
      - if: $PIPELINE_NAME == "simple_dependency"

job:
  tags: [powershell]
  when: manual
  script:
    - echo "executing pipeline $PIPELINE_NAME"