stages:
  - .pre
  - build
  - .post

prepare_jfrog_cli:
  stage: .pre
  tags: [powershell]    
  needs: ["start_pipeline"]
  when: manual
  script:
    # Install JFrog CLI
    # Configure Artifactory instance with JFrog CLI
    - jf rt config --url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASSWORD
    - jf rt c show
    


upload_files:
  stage: build
  tags: [powershell]    
  needs: ["start_pipeline"]
  when: manual
  script: 
    - jf rt u "../appfiles" $ARTIFACTORY_REPO_KEY


say_success:
  stage: .post
  tags: [powershell]  
  needs: ["upload_files"]
  script: powershell .\scripts\date.ps1