stages:
  - .pre
  - build-gitlab
  - build-artifactory
  - .post
  
create_artifact_gitlab:
  stage: build-gitlab
  tags: [powershell]
  needs: ["start_pipeline"]
  when: manual
  script: 
    - Compress-Archive -Path .\appfiles -DestinationPath .\artifacts\"appfiles-$env:CI_JOB_NAME-$env:CI_JOB_ID".zip
  artifacts:
    paths:
      - .\artifacts\"appfiles-$env:CI_JOB_NAME-$env:CI_JOB_ID".zip
    expire_in: 1 week

create_artifact_artifactory:
  stage: build-artifactory
  tags: [powershell]
  needs: ["create_artifact_gitlab"]
  when: manual
  script: 
    - jfrog rt u --build-name="appfiles-$env:CI_JOB_NAME-$env:CI_JOB_ID" --build-number="$env:CI_JOB_ID" .\artifacts\appfiles.zip $env:ARTIFACTORY_REPO_KEY